### PR TITLE
Fixes #12199 - rails 4 migration errors

### PR DESCRIPTION
**Pull request by johnpmitsch**
There are actually two parts to the issue of not being able to migrate with this branch. The first  is https://gist.github.com/eLobato/0f5db50b5c93cc6c277c and can be temporarily fixed with https://github.com/rails/sass-rails/issues/136#issuecomment-23677619 I am not sure of a long term fix for that atm.

Once that is patched, this error https://gist.github.com/johnpmitsch/96e5ba3629890931193a happens on a migration. This will fix that error by changing the Migrator class initializer arguments which have changed from [rails 3](http://www.rubydoc.info/docs/rails/3.2.8/ActiveRecord/Migrator#initialize-instance_method) to [rails 4 ](http://www.rubydoc.info/docs/rails/4.1.7/ActiveRecord/Migrator#initialize-instance_method)

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@eLobato I don't see an easy solution that would work on both rails 3 and rails 4, unless you can think of anything?

**Comment by dLobatog** [comment]
@johnpmitsch :+1: thanks , I'll clean up the branch in a bit and merge it. :smile:

**Comment by unorthodoxgeek** [comment]
@johnpmitsch - meanwhile, cherry-picking this commit into your working VM allows you guys to work on the Katello rails4 branch with the rails4_from_scratch branch?

**Comment by johnpmitsch** [comment]
@unorthodoxgeek yes, as long as we applied the fix for the actionpack gem I mentioned, we can cherry pick this commit and have a working rails4_from_scratch branch

**Comment by dLobatog** [comment]
Merged as https://github.com/dLobatog/foreman/commit/a47cd913e45dc74b71a822054c3ad90fda70e305,  thanks @johnpmitsch !

**Comment by cpeters** [comment]
I spent some time tinkering with rails initializers in an attempt to modify the actionpack gem to support this fix. Then I stopped because I don't think we should implement the fix at that level as it might have implications in the loading of other middleware now or in the future. I think the reasonable approach in this situation is a hack the loading of the sass middleware itself as show here

  if defined?(Sass::Plugin::Rack)
    app.config.middleware.delete(Sass::Plugin::Rack)
  end

**Pull request closed without merging**
